# Generated by Django 4.2.7 on 2024-05-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
